<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::table('staff', function (Blueprint $table) {
            // National ID card scan (image or PDF), as uploaded.
            $table->string('nida_card_path')->nullable()->after('contract_amount');

            // Curriculum Vitae (PDF).
            $table->string('cv_path')->nullable()->after('nida_card_path');

            // Merged single PDF containing all uploaded professional
            // certificates - generated by CertificateMergeService from
            // the individual files uploaded via the "Add Certificates"
            // multi-file picker.
            $table->string('certificates_path')->nullable()->after('cv_path');
        });
    }

    public function down(): void
    {
        Schema::table('staff', function (Blueprint $table) {
            $table->dropColumn(['nida_card_path', 'cv_path', 'certificates_path']);
        });
    }
};
